name: PR - Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci-cd:
    name: Pull request
    uses: ./.github/workflows/ci-cd.yml
    secrets: inherit
