name: Production - Build, test, and deploy

on:
  release:
    types:
      - released
  workflow_dispatch

jobs:
  ci-cd:
    name: Release
    uses: ./.github/workflows/ci-cd.yml
    secrets: inherit
    with:
      deploy: true
