name: Build and test to release new package

on:
  release:
    types:
      - released

jobs:
  ci-cd:
    name: CI-CD
    uses: ./.github/workflows/ci-cd.yml
    secrets: inherit
    with:
      deploy: true
      is_staging: true
